import Head from 'next/head'
//import Image from 'next/image'
import UserList from './userList';
import Layout from '@/components/layout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Git Buddies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        
        <UserList/>
        
      </Layout>
    </>
  )
}
